apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-pvc
  namespace: jenkins
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi # ขอพื้นที่ 10 GB (ปรับขนาดได้ตามต้องการ)
  # หากคุณมี StorageClass เฉพาะ ให้ระบุ